-- Venues

INSERT INTO venues (id, name, city, raw_names) VALUES
  (1, 'ACA-VDCA Stadium', 'Visakhapatnam', ARRAY['Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium', 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam']),
  (2, 'Arun Jaitley Stadium', 'Delhi', ARRAY['Arun Jaitley Stadium', 'Arun Jaitley Stadium, Delhi', 'Feroz Shah Kotla']),
  (3, 'Barabati Stadium', 'Cuttack', ARRAY['Barabati Stadium']),
  (4, 'Barsapara Stadium', 'Guwahati', ARRAY['Barsapara Cricket Stadium, Guwahati']),
  (5, 'Brabourne Stadium', 'Mumbai', ARRAY['Brabourne Stadium', 'Brabourne Stadium, Mumbai']),
  (6, 'Buffalo Park', 'East London', ARRAY['Buffalo Park']),
  (7, 'DY Patil Stadium', 'Mumbai', ARRAY['Dr DY Patil Sports Academy', 'Dr DY Patil Sports Academy, Mumbai']),
  (8, 'Diamond Oval', 'Kimberley', ARRAY['De Beers Diamond Oval']),
  (9, 'Dubai International Stadium', 'Dubai', ARRAY['Dubai International Cricket Stadium']),
  (10, 'Eden Gardens', 'Kolkata', ARRAY['Eden Gardens', 'Eden Gardens, Kolkata']),
  (11, 'Ekana Stadium', 'Lucknow', ARRAY['Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow']),
  (12, 'Green Park', 'Kanpur', ARRAY['Green Park']),
  (13, 'HPCA Stadium', 'Dharamsala', ARRAY['Himachal Pradesh Cricket Association Stadium', 'Himachal Pradesh Cricket Association Stadium, Dharamsala']),
  (14, 'Holkar Cricket Stadium', 'Indore', ARRAY['Holkar Cricket Stadium']),
  (15, 'JSCA Stadium', 'Ranchi', ARRAY['JSCA International Stadium Complex']),
  (16, 'Kingsmead', 'Durban', ARRAY['Kingsmead']),
  (17, 'M Chinnaswamy Stadium', 'Bengaluru', ARRAY['M Chinnaswamy Stadium', 'M Chinnaswamy Stadium, Bengaluru', 'M.Chinnaswamy Stadium']),
  (18, 'MA Chidambaram Stadium', 'Chennai', ARRAY['MA Chidambaram Stadium', 'MA Chidambaram Stadium, Chepauk', 'MA Chidambaram Stadium, Chepauk, Chennai']),
  (19, 'MCA Stadium', 'Pune', ARRAY['Maharashtra Cricket Association Stadium', 'Maharashtra Cricket Association Stadium, Pune', 'Subrata Roy Sahara Stadium']),
  (20, 'MYSI Stadium', 'Mullanpur', ARRAY['Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur', 'Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh']),
  (21, 'Narendra Modi Stadium', 'Ahmedabad', ARRAY['Narendra Modi Stadium, Ahmedabad', 'Sardar Patel Stadium, Motera']),
  (22, 'Nehru Stadium', 'Kochi', ARRAY['Nehru Stadium']),
  (23, 'Newlands', 'Cape Town', ARRAY['Newlands']),
  (24, 'OUTsurance Oval', 'Bloemfontein', ARRAY['OUTsurance Oval']),
  (25, 'PCA Stadium', 'Mohali', ARRAY['Punjab Cricket Association IS Bindra Stadium', 'Punjab Cricket Association IS Bindra Stadium, Mohali', 'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh', 'Punjab Cricket Association Stadium, Mohali']),
  (26, 'Rajiv Gandhi International Stadium', 'Hyderabad', ARRAY['Rajiv Gandhi International Stadium', 'Rajiv Gandhi International Stadium, Uppal', 'Rajiv Gandhi International Stadium, Uppal, Hyderabad']),
  (27, 'SCA Stadium', 'Rajkot', ARRAY['Saurashtra Cricket Association Stadium']),
  (28, 'Sawai Mansingh Stadium', 'Jaipur', ARRAY['Sawai Mansingh Stadium', 'Sawai Mansingh Stadium, Jaipur']),
  (29, 'Sharjah Cricket Stadium', 'Sharjah', ARRAY['Sharjah Cricket Stadium']),
  (30, 'Sheikh Zayed Stadium', 'Abu Dhabi', ARRAY['Sheikh Zayed Stadium', 'Zayed Cricket Stadium, Abu Dhabi']),
  (31, 'St George''s Park', 'Gqeberha', ARRAY['St George''s Park']),
  (32, 'SuperSport Park', 'Centurion', ARRAY['SuperSport Park']),
  (33, 'VCA Stadium', 'Nagpur', ARRAY['Vidarbha Cricket Association Stadium, Jamtha']),
  (34, 'VNS Stadium', 'Raipur', ARRAY['Shaheed Veer Narayan Singh International Stadium']),
  (35, 'Wanderers Stadium', 'Johannesburg', ARRAY['New Wanderers Stadium']),
  (36, 'Wankhede Stadium', 'Mumbai', ARRAY['Wankhede Stadium', 'Wankhede Stadium, Mumbai']);
